name: Murder Case Scraper Parallel Batches

on:
  workflow_dispatch:

jobs:
  run-batches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        range: [
          "0-9999", "10000-19999"
        ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --skip-lock

      - name: Extract batch range
        id: range
        run: |
          START=$(echo "${{ matrix.range }}" | cut -d '-' -f 1)
          END=$(echo "${{ matrix.range }}" | cut -d '-' -f 2)
          echo "start=$START" >> $GITHUB_OUTPUT
          echo "end=$END" >> $GITHUB_OUTPUT

      - name: Run scraper
        env:
          START: ${{ steps.range.outputs.start }}
          END: ${{ steps.range.outputs.end }}
        run: pipenv run python scraper.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v4
        with:
          name: murder-charges-${{ steps.range.outputs.start }}-${{ steps.range.outputs.end }}
          path: murder_charges.csv
