name: Murder Case Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --skip-lock

      - name: Write Google credentials
        run: echo "${{ secrets.GOOGLE_CREDS_BASE64 }}" | base64 -d > google-creds.json

      - name: Run scraper
        run: pipenv run python scraper.py
