name: Murder Case Scraper

on:
  workflow_dispatch:
  schedule:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --skip-lock

      - name: Run scraper
        run: pipenv run python scraper.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v4
        with:
          name: murder-charges-csv
          path: murder_charges.csv
